In [1]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
from datetime import datetime

In [2]:
url = "https://r.jina.ai/https://www.ccny.cuny.edu/registrar/fall"

r = requests.get(url)

print(r.status_code)

200

In [3]:
start = r.text.find("August 01")

print(start)

34390

In [4]:
lines = r.text.splitlines()

#beginning of table
beginning = next(i for i, line in enumerate(lines) if "August 01" in line)

#end of table
end = next(i for i, line in enumerate(lines[beginning:], start) if "January 1, 2022" in line)

#only calendar rows
calendar_lines = lines[beginning:end + 1]

for line in calendar_lines:
    print(line)

| **August 01** | **Sunday** | **Application for degree for January and February 2022 begins** |
| August 18 | Wednesday | Last day to apply for Study Abroad |
| **August 24** | **Tuesday** | **Last day of Registration; Last day to file ePermit for the Fall 2021; Last day to drop classes for 100% tuition refund;** |
| August 25 | Wednesday | Start of Fall Term; Classes begin; Initial Registration Appeals begin; |
| **August 25 - 31** | **Wednesday - Tuesday** | **Change of program period; late fees apply** |
| August 26 | Thursday | Last day for Independent Study |
| **August 28** | **Saturday** | **First day of Saturday Classes** |
| August 31 | Tuesday | Last day to add a class to an existing enrollment; Last day for 75% tuition refund; Financial Aid Certification Enrollment Status date; Last day to apply for Audit option; Last day to drop without the grade of 'WD'; Initial Registration Appeals end; |
| **September 01** | **Wednesday** | **Verification of Enrollment rosters available to faculty; Course Withdrawal drop period begins (A grade of 'WD' is assigned to students who officially drop a class);** |
| September 03 - 08 | Friday - Wednesday | No classes scheduled |
| **September 06** | **Monday** | **College Closed; Last day for 50% tuition refund;** |
| September 09 | Thursday | Freshman Convocation |
| **September 14** | **Tuesday** | **Last day for 25% tuition refund; Census date; Last day to change or declare a major/minor to be effective in Fall 2021; Last day to drop without the grade of 'W'; Course Withdrawal drop period ends (Last day for 'WD' grades); Verification of Enrollment Rosters Dues from Faculty;** |
| September 15 | Wednesday | Assignment of 'WN' grades for non-attendance; Course Withdrawal period begins (A grade of 'W' is assigned to students who officially drop a class) - No Refund; 100% Tuition obligation for course drops; |
| **September 15 - 16** | **Wednesday - Thursday** | **No classes scheduled** |
| September 23 | Thursday | Last day to submit proof of immunization for NYS residents; |
| **September 24** | **Friday** | **Assignment of 'WA' grades for immunization non-compliance** |
| October 01 | Friday | Advising month begins for Spring and Winter enrollment |
| **October 08** | **Friday** | **Deadline for filing application for degree for January and February 2022; Last day to submit proof of immunization for non-NYS residents;** |
| October 11 | Monday | College Closed |
| **November 01** | **Monday** | **'INC' grades for Spring 2021 and Winter 2021 for Undergraduate students convert to 'FIN'; 'INC' grades for Summer 2020 and Fall 2020 for Graduate students convert to 'FIN';** |
| November 02 | Tuesday | Registration appointments for Winter and Spring 2022 begin for continuing students. Check your CUNYFirst account for your appointment date and time. |
| **November 04** | **Thursday** | **Last day to file for P/NC option** |
| November 06 | Saturday | 60% Date of the term |
| **November 23** | **Tuesday** | **'INC' grades for Summer 2021 for Undergraduate students convert to 'FIN'** |
| November 25 - 28 | Thursday - Sunday | College Closed |
| **December 11** | **Saturday** | **Last day of Saturday Classes** |
| December 13 | Monday | Course Withdrawal period ends (Last day to withdraw from a class with the grade of 'W'); Last day of Classes; |
| **December 14** | **Tuesday** | **Reading Day** |
| December 15 - 21 | Wednesday - Tuesday | Final Examinations |
| **December 21** | **Tuesday** | **End of Term** |
| December 24 - 25 | Friday - Saturday | College Closed |
| **December 27** | **Monday** | **College Closed** |
| December 28 | Tuesday | Final Grade Submission Deadline for Fall 2021 |
| **December 31** | **Friday** | **College Closed** |
| January 1, 2022 | Saturday | College Closed; Fall 2021 Degree Conferral Date; |

*   [![Image 33: Share to Twitter](https://www.ccny.cuny.edu/themes/custom/ccny_theme/dist/assets/icon-twitter-purple-hollow.svg)](https://www.addtoany.com/add_to/x?linkurl=https%3A%2F%2Fwww.ccny.cuny.edu%2Fregistrar%2Ffall)
*   [![Image 34: Share to Facebook](https://www.ccny.cuny.edu/themes/custom/ccny_theme/dist/assets/icon-facebook-purple-hollow.svg)](https://www.addtoany.com/add_to/facebook?linkurl=https%3A%2F%2Fwww.ccny.cuny.edu%2Fregistrar%2Ffall)
*   [![Image 35: Share to LinkedIn](https://www.ccny.cuny.edu/themes/custom/ccny_theme/dist/assets/icon-linkedin-purple-hollow.svg)](https://www.addtoany.com/add_to/linkedin?linkurl=https%3A%2F%2Fwww.ccny.cuny.edu%2Fregistrar%2Ffall)
*   [![Image 36: Share to Email](https://www.ccny.cuny.edu/themes/custom/ccny_theme/dist/assets/icon-mail-purple-hollow.svg)](https://www.addtoany.com/add_to/email?linkurl=https%3A%2F%2Fwww.ccny.cuny.edu%2Fregistrar%2Ffall)

Last Updated: 06/21/2026 03:44

We use cookies and other tracking technologies to improve your browsing experience on our website, analyze our website traffic, and understand where our visitors are coming from. If you choose "ACCEPT ALL", you consent to the use of all cookies. You can accept and reject individual cookie types and revoke your consent for the future at any time at "Settings".
*   [Privacy policy](https://www.ccny.cuny.edu/about/websiteprivacy)
*   [About us](https://www.ccny.cuny.edu/about)

Cookie settings Deny all Accept all

![Image 37: The City College of New York](https://www.ccny.cuny.edu/themes/custom/ccny_theme/dist/assets/seal.svg)

 The City College of New York
 160 Convent Avenue New York, NY 10031

 p: [212.650.7000](tel:212.650.7000 "212.650.700")

[![Image 38: The City University of New York](https://www.ccny.cuny.edu/themes/custom/ccny_theme/dist/assets/CUNY_Logo_with%20Name_Right_White_RGB.svg)](https://www.cuny.edu/)

###### Students

*   [Email](https://citymail.ccny.cuny.edu/ "Email")
*   [Academic Calendar](https://www.ccny.cuny.edu/registrar/academic-calendar "Academic Calendar")
*   [Courses - CCNY Bulletin](https://www.ccny.cuny.edu/registrar/bulletins "Courses - CCNY Bulletin")
*   [Courses - CUNY list](https://globalsearch.cuny.edu/ "Courses - CUNY list")
*   [Apply Now - Undergraduate](http://www2.cuny.edu/admissions/undergraduate/apply/ "Apply Now - Undergraduate")
*   [Apply Now - Graduate](https://app.applyyourself.com/AYApplicantLogin/fl_ApplicantConnectLogin.asp?id=CUNYCCNYG "Apply Now - Graduate")
*   [Libraries](https://www.ccny.cuny.edu/library "Libraries")
*   [Benny's Campus Store](https://www.ccny.cuny.edu/bennys "Benny's Campus Store")
*   [Registrar](https://www.ccny.cuny.edu/registrar "Registrar")
*   [Student Employment](https://www.ccny.cuny.edu/financialaid/federal-work-study-at-ccny "Student Employment")

###### Faculty & Staff

*   [Webmail](https://webmail.ccny.cuny.edu/owa/auth/logon.aspx?replaceCurrent=1&url=https%3a%2f%2fwebmail.ccny.cuny.edu%2fowa%2f "Webmail")
*   [Directory](https://www.ccny.cuny.edu/people "Directory")
*   [Diversity & Compliance](https://www.ccny.cuny.edu/affirmativeaction "Diversity & Compliance")
*   [Employee Resources](https://www.ccny.cuny.edu/hr/resources-for-employees "Employee Resources")
*   [Faculty Resources](https://www.ccny.cuny.edu/academicaffairs/faculty-resources "Faculty Resources")
*   [Human Resources](https://www.ccny.cuny.edu/hr "Human Resources")
*   [Payroll](https://www.ccny.cuny.edu/payroll "Payroll")
*   [Offices and Services](https://www.ccny.cuny.edu/about/offices-services "Offices and Services")
*   [Work at CCNY](https://www2.cuny.edu/employment/ "Work at CCNY")

###### Resources

*   [CCNY Navigate](https://www.ccny.cuny.edu/ccny-navigate "CCNY Navigate")
*   [Schedule a tour - Undergraduate](https://www.ccny.cuny.edu/admissions/undergraduate-campus-tours "Schedule a tour - Undergraduate")
*   [Contact Us](https://www.ccny.cuny.edu/about/contact "Contact Us")
*   [Giving](https://www.ccny.cuny.edu/giving "Giving")
*   [Safety](https://www.ccny.cuny.edu/safety "Safety")
*   [CCNY and CUNY Policies](https://www.ccny.cuny.edu/about/policies "CCNY and CUNY Policies")
*   [Privacy Policy](https://www.ccny.cuny.edu/about/websiteprivacy "Privacy Policy")
*   [Employer Services](https://www.ccny.cuny.edu/cpdi/employer-services "Employer Services")
*   [Information Technology](https://www.ccny.cuny.edu/it "Information Technology")
*   [Discrimination and Retaliation Reporting Portal](https://cuny.guardianconduct.com/incident-reporting "Discrimination and Retaliation Reporting Portal")
*   [Freedom of Information Law](https://www.ccny.cuny.edu/counsel/foil "Freedom of Information Law ")
*   [Consumer Information](https://www.ccny.cuny.edu/academicaffairs/consumer-information "Consumer Information")

###### Accessibility

*   [Accessibility Statement](https://www.ccny.cuny.edu/about/accessible-digital-content-policy "Accessibility Statement")
*   [Loaner Devices](https://portal.ccny.cuny.edu/depts/oit/cuny_loaner/login.php "Loaner Devices")

*   [Text Only Version](https://www.textise.net/showText.aspx?strURL=https%3A%2F%2Fwww.ccny.cuny.edu%2Fregistrar%2Ffall "Text Only Version")

[![Image 39: Mixpanel Mobile Analytics](https://cdn.mxpnl.com/site_media/images/partner/badge_light.png)](https://mixpanel.com/f/partner)

*   [![Image 40: Instagram](https://www.ccny.cuny.edu/themes/custom/ccny_theme/dist/assets/icon-instagram.svg)](https://instagram.com/ccnycitycollege/)
*   [![Image 41: Facebook](https://www.ccny.cuny.edu/themes/custom/ccny_theme/dist/assets/icon-facebook.svg)](https://www.facebook.com/pages/The-City-College-of-New-York/170858093839)
*   [![Image 42: LinkedIn](https://www.ccny.cuny.edu/themes/custom/ccny_theme/dist/assets/icon-linkedin.svg)](https://www.linkedin.com/school/city-college-of-new-york/)
*   [![Image 43: YouTube](https://www.ccny.cuny.edu/themes/custom/ccny_theme/dist/assets/icon-youtube.svg)](https://www.youtube.com/user/citycollegeofny)

### Students

*   [Email](https://citymail.ccny.cuny.edu/ "Email")
*   [Academic Calendar](https://www.ccny.cuny.edu/registrar/academic-calendar "Academic Calendar")
*   [Courses - CCNY Bulletin](https://www.ccny.cuny.edu/registrar/bulletins "Courses - CCNY Bulletin")
*   [Courses - CUNY list](https://globalsearch.cuny.edu/ "Courses - CUNY list")
*   [Apply Now - Undergraduate](http://www2.cuny.edu/admissions/undergraduate/apply/ "Apply Now - Undergraduate")
*   [Apply Now - Graduate](https://app.applyyourself.com/AYApplicantLogin/fl_ApplicantConnectLogin.asp?id=CUNYCCNYG "Apply Now - Graduate")
*   [Libraries](https://www.ccny.cuny.edu/library "Libraries")
*   [Benny's Campus Store](https://www.ccny.cuny.edu/bennys "Benny's Campus Store")
*   [Registrar](https://www.ccny.cuny.edu/registrar "Registrar")
*   [Student Employment](https://www.ccny.cuny.edu/financialaid/federal-work-study-at-ccny "Student Employment")

### Faculty & Staff

*   [Webmail](https://webmail.ccny.cuny.edu/owa/auth/logon.aspx?replaceCurrent=1&url=https%3a%2f%2fwebmail.ccny.cuny.edu%2fowa%2f "Webmail")
*   [Directory](https://www.ccny.cuny.edu/people "Directory")
*   [Diversity & Compliance](https://www.ccny.cuny.edu/affirmativeaction "Diversity & Compliance")
*   [Employee Resources](https://www.ccny.cuny.edu/hr/resources-for-employees "Employee Resources")
*   [Faculty Resources](https://www.ccny.cuny.edu/academicaffairs/faculty-resources "Faculty Resources")
*   [Human Resources](https://www.ccny.cuny.edu/hr "Human Resources")
*   [Payroll](https://www.ccny.cuny.edu/payroll "Payroll")
*   [Offices and Services](https://www.ccny.cuny.edu/about/offices-services "Offices and Services")
*   [Work at CCNY](https://www2.cuny.edu/employment/ "Work at CCNY")

### Resources

*   [CCNY Navigate](https://www.ccny.cuny.edu/ccny-navigate "CCNY Navigate")
*   [Schedule a tour - Undergraduate](https://www.ccny.cuny.edu/admissions/undergraduate-campus-tours "Schedule a tour - Undergraduate")
*   [Contact Us](https://www.ccny.cuny.edu/about/contact "Contact Us")
*   [Giving](https://www.ccny.cuny.edu/giving "Giving")
*   [Safety](https://www.ccny.cuny.edu/safety "Safety")
*   [CCNY and CUNY Policies](https://www.ccny.cuny.edu/about/policies "CCNY and CUNY Policies")
*   [Privacy Policy](https://www.ccny.cuny.edu/about/websiteprivacy "Privacy Policy")
*   [Employer Services](https://www.ccny.cuny.edu/cpdi/employer-services "Employer Services")
*   [Information Technology](https://www.ccny.cuny.edu/it "Information Technology")
*   [Discrimination and Retaliation Reporting Portal](https://cuny.guardianconduct.com/incident-reporting "Discrimination and Retaliation Reporting Portal")
*   [Freedom of Information Law](https://www.ccny.cuny.edu/counsel/foil "Freedom of Information Law ")
*   [Consumer Information](https://www.ccny.cuny.edu/academicaffairs/consumer-information "Consumer Information")

### Accessibility

*   [Accessibility Statement](https://www.ccny.cuny.edu/about/accessible-digital-content-policy "Accessibility Statement")
*   [Text Only Version](https://www.textise.net/showText.aspx?strURL=https%3A%2F%2Fwww.ccny.cuny.edu%2Fregistrar%2Ffall "Text Only Version")
*   [Loaner Devices](https://portal.ccny.cuny.edu/depts/oit/cuny_loaner/login.php "Loaner Devices")
*   [Text Only Version](https://www.textise.net/showText.aspx?strURL=https%3A%2F%2Fwww.ccny.cuny.edu%2Fregistrar%2Ffall "Text Only Version")

[![Image 44: Mixpanel Mobile Analytics](https://cdn.mxpnl.com/site_media/images/partner/badge_light.png)](https://mixpanel.com/f/partner)

*   [![Image 45: Instagram](https://www.ccny.cuny.edu/themes/custom/ccny_theme/dist/assets/icon-instagram.svg)](https://instagram.com/ccnycitycollege/)
*   [![Image 46: Facebook](https://www.ccny.cuny.edu/themes/custom/ccny_theme/dist/assets/icon-facebook.svg)](https://www.facebook.com/pages/The-City-College-of-New-York/170858093839)
*   [![Image 47: LinkedIn](https://www.ccny.cuny.edu/themes/custom/ccny_theme/dist/assets/icon-linkedin.svg)](https://www.linkedin.com/school/city-college-of-new-york/)
*   [![Image 48: YouTube](https://www.ccny.cuny.edu/themes/custom/ccny_theme/dist/assets/icon-youtube.svg)](https://www.youtube.com/user/citycollegeofny)

© The City College of New York. All rights reserved.

In [5]:
data = []

for line in calendar_lines:
    line = line.replace("**", "").strip()

    if "|" not in line:
        continue

    #remove | 
    line = line.strip("|")

    #columns
    parts = [part.strip() for part in line.split("|")]

    if len(parts) >= 3:
        date_text = parts[0]
        dow = parts[1]
        text = parts[2]

        data.append([date_text, dow, text])

df = pd.DataFrame(data, columns=["date", "day", "text"])

df

,date,day,text
0,August 01,Sunday,Application for degree for January and Februar...
1,August 18,Wednesday,Last day to apply for Study Abroad
2,August 24,Tuesday,Last day of Registration; Last day to file ePe...
3,August 25,Wednesday,Start of Fall Term; Classes begin; Initial Reg...
4,August 25 - 31,Wednesday - Tuesday,Change of program period; late fees apply
5,August 26,Thursday,Last day for Independent Study
6,August 28,Saturday,First day of Saturday Classes
7,August 31,Tuesday,Last day to add a class to an existing enrollm...
8,September 01,Wednesday,Verification of Enrollment rosters available t...
9,September 03 - 08,Friday - Wednesday,No classes scheduled
10,September 06,Monday,College Closed; Last day for 50% tuition refund;
11,September 09,Thursday,Freshman Convocation
12,September 14,Tuesday,Last day for 25% tuition refund; Census date; ...
13,September 15,Wednesday,Assignment of 'WN' grades for non-attendance; ...
14,September 15 - 16,Wednesday - Thursday,No classes scheduled
15,September 23,Thursday,Last day to submit proof of immunization for N...
16,September 24,Friday,Assignment of 'WA' grades for immunization non...
17,October 01,Friday,Advising month begins for Spring and Winter en...
18,October 08,Friday,Deadline for filing application for degree for...
19,October 11,Monday,College Closed
20,November 01,Monday,'INC' grades for Spring 2021 and Winter 2021 f...
21,November 02,Tuesday,Registration appointments for Winter and Sprin...
22,November 04,Thursday,Last day to file for P/NC option
23,November 06,Saturday,60% Date of the term
24,November 23,Tuesday,'INC' grades for Summer 2021 for Undergraduate...
25,November 25 - 28,Thursday - Sunday,College Closed
26,December 11,Saturday,Last day of Saturday Classes
27,December 13,Monday,Course Withdrawal period ends (Last day to wit...
28,December 14,Tuesday,Reading Day
29,December 15 - 21,Wednesday - Tuesday,Final Examinations
30,December 21,Tuesday,End of Term
31,December 24 - 25,Friday - Saturday,College Closed
32,December 27,Monday,College Closed
33,December 28,Tuesday,Final Grade Submission Deadline for Fall 2021
34,December 31,Friday,College Closed
35,"January 1, 2022",Saturday,College Closed; Fall 2021 Degree Conferral Date;

In [6]:
lines = r.text.splitlines()

beginning = next(i for i, line in enumerate(lines) if "August 01" in line)
end = next(i for i, line in enumerate(lines[beginning:], start) 
           if "January 1, 2022" in line)

calendar_lines = lines[beginning:end + 1]

In [7]:
#for ranges of dates
df["date"] = df["date"].str.split(" - ").str[0]

print(df["date"].tolist())

['August 01', 'August 18', 'August 24', 'August 25', 'August 25', 'August 26', 'August 28', 'August 31', 'September 01', 'September 03', 'September 06', 'September 09', 'September 14', 'September 15', 'September 15', 'September 23', 'September 24', 'October 01', 'October 08', 'October 11', 'November 01', 'November 02', 'November 04', 'November 06', 'November 23', 'November 25', 'December 11', 'December 13', 'December 14', 'December 15', 'December 21', 'December 24', 'December 27', 'December 28', 'December 31', 'January 1, 2022']

In [8]:
def add_year(date_string):
    if "," in date_string:
        return date_string
    else:
        return date_string + ", 2021"

df["date"] = df["date"].apply(add_year)

print(df["date"].tolist())

['August 01, 2021', 'August 18, 2021', 'August 24, 2021', 'August 25, 2021', 'August 25, 2021', 'August 26, 2021', 'August 28, 2021', 'August 31, 2021', 'September 01, 2021', 'September 03, 2021', 'September 06, 2021', 'September 09, 2021', 'September 14, 2021', 'September 15, 2021', 'September 15, 2021', 'September 23, 2021', 'September 24, 2021', 'October 01, 2021', 'October 08, 2021', 'October 11, 2021', 'November 01, 2021', 'November 02, 2021', 'November 04, 2021', 'November 06, 2021', 'November 23, 2021', 'November 25, 2021', 'December 11, 2021', 'December 13, 2021', 'December 14, 2021', 'December 15, 2021', 'December 21, 2021', 'December 24, 2021', 'December 27, 2021', 'December 28, 2021', 'December 31, 2021', 'January 1, 2022']

In [9]:
df

,date,day,text
0,"August 01, 2021",Sunday,Application for degree for January and Februar...
1,"August 18, 2021",Wednesday,Last day to apply for Study Abroad
2,"August 24, 2021",Tuesday,Last day of Registration; Last day to file ePe...
3,"August 25, 2021",Wednesday,Start of Fall Term; Classes begin; Initial Reg...
4,"August 25, 2021",Wednesday - Tuesday,Change of program period; late fees apply
5,"August 26, 2021",Thursday,Last day for Independent Study
6,"August 28, 2021",Saturday,First day of Saturday Classes
7,"August 31, 2021",Tuesday,Last day to add a class to an existing enrollm...
8,"September 01, 2021",Wednesday,Verification of Enrollment rosters available t...
9,"September 03, 2021",Friday - Wednesday,No classes scheduled
10,"September 06, 2021",Monday,College Closed; Last day for 50% tuition refund;
11,"September 09, 2021",Thursday,Freshman Convocation
12,"September 14, 2021",Tuesday,Last day for 25% tuition refund; Census date; ...
13,"September 15, 2021",Wednesday,Assignment of 'WN' grades for non-attendance; ...
14,"September 15, 2021",Wednesday - Thursday,No classes scheduled
15,"September 23, 2021",Thursday,Last day to submit proof of immunization for N...
16,"September 24, 2021",Friday,Assignment of 'WA' grades for immunization non...
17,"October 01, 2021",Friday,Advising month begins for Spring and Winter en...
18,"October 08, 2021",Friday,Deadline for filing application for degree for...
19,"October 11, 2021",Monday,College Closed
20,"November 01, 2021",Monday,'INC' grades for Spring 2021 and Winter 2021 f...
21,"November 02, 2021",Tuesday,Registration appointments for Winter and Sprin...
22,"November 04, 2021",Thursday,Last day to file for P/NC option
23,"November 06, 2021",Saturday,60% Date of the term
24,"November 23, 2021",Tuesday,'INC' grades for Summer 2021 for Undergraduate...
25,"November 25, 2021",Thursday - Sunday,College Closed
26,"December 11, 2021",Saturday,Last day of Saturday Classes
27,"December 13, 2021",Monday,Course Withdrawal period ends (Last day to wit...
28,"December 14, 2021",Tuesday,Reading Day
29,"December 15, 2021",Wednesday - Tuesday,Final Examinations
30,"December 21, 2021",Tuesday,End of Term
31,"December 24, 2021",Friday - Saturday,College Closed
32,"December 27, 2021",Monday,College Closed
33,"December 28, 2021",Tuesday,Final Grade Submission Deadline for Fall 2021
34,"December 31, 2021",Friday,College Closed
35,"January 1, 2022",Saturday,College Closed; Fall 2021 Degree Conferral Date;